### ISSUE TITLE
Flow burst duration is not implemented

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/snappi-ixnetwork#367]
# Issue
The Flow.Burst schema object has a property `bursts` which appears to be missing from the main and open-traffic-generator branches.  Sonic-mgmt tests are currently being developed that uses the Burst feature and will need access to the `bursts` property.

```yaml
Flow.Burst:
  properties:
    bursts:
      description: >-
        The number of packet bursts transmitted per flow.
        A value of 0 implies continuous burst of packets.
      type: integer
      default: 0
```
